### ISSUE TITLE
[FR] Change to a more standard file format to storage snippets

### ISSUE THREAD

**Issue by proItheus** [artisticat1/obsidian-latex-suite#66]
Very happy that #39 be implemented! Now I can use ultisnips in vim to quickly creat snippets :smile:.

However, current snippet file use a strange format (array in js?) , thus for syntax highlighting and checking to work, we have to write relevent configs from scrach, which is a REALLY pain...

I think it's better to switch to some more standard formats to solve that. Switch to `json` may only require minimal effort, though it appears to not support comments?

I'm personally in favor of `toml` for it's readability and native support of comments. We may specify a snippet like this:
```toml
# some comment
[[snip]]
trigger = "mk"
replace = "$$0$"
options = "mA"
```
